name = "raf-park"
total-spaces = 130
total-cars = 0
location = 'L306'
topic-root = "lot"
broker = 'localhost'
port = 1883
topic-qualifier = 'entry'
is_stuff = false
# boolean value must be lowercase for toml